'use strict';
// Deterministic conversion. Source is a trusted file in this repository.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, 'assets/js/data.js'), 'utf8'), context);
const data = JSON.parse(JSON.stringify(context.window));
const normalize = image => image.replace(/^\.\.\//, '/');
const components = data.COMPONENTS_DATA.map(c => ({ ...c, image: normalize(c.image) }));
for (const [id, name, image] of [
  ['caster-wheel', 'Bánh tự do', '/assets/images/assembly/chassis-2wd.png'],
  ['arm-frame', 'Bộ khung cánh tay', '/assets/images/robots/robot-arm-mini.png'],
  ['mini-gripper', 'Bộ kẹp mini', '/assets/images/robots/robot-arm-mini.png'],
  ['power-5v', 'Nguồn 5V phù hợp', '/assets/images/robots/robot-arm-mini.png']
]) components.push({ id, name, category: id === 'power-5v' ? 'Nguồn điện' : 'Cơ khí', image, description: `${name}. Ảnh minh họa theo cụm lắp ráp; chọn kích thước và tải phù hợp bộ kit.`, specs: { 'Ghi chú': 'Đối chiếu bộ kit thực tế trước khi lắp ráp.' } });
const aliases = { 'Khung xe 2 bánh': 'chassis-2wd', 'Arduino Uno': 'arduino-uno', 'Động cơ DC': 'dc-motor', 'Bánh xe': 'wheel', 'Bánh tự do': 'caster-wheel', 'Cảm biến dò line': 'line-sensor', 'Module L298N': 'l298n', 'Hộp pin': 'battery-holder', 'Cảm biến siêu âm HC-SR04': 'hc-sr04', 'Bộ khung cánh tay': 'arm-frame', 'Động cơ servo': 'sg90', 'Bộ kẹp mini': 'mini-gripper', 'Nguồn 5V phù hợp': 'power-5v' };
const robots = [], steps = [], relations = [], library = [];
for (const model of data.ROBOT_MODELS) {
  const { parts, steps: instructions, ...robot } = model;
  robot.image = normalize(robot.image);
  robots.push(robot);
  parts.forEach(part => {
    const componentId = aliases[part.name];
    if (!components.some(c => c.id === componentId)) throw Error(`Thiếu mapping: ${part.name}`);
    relations.push({ robotId: robot.id, componentId, quantity: part.quantity });
  });
  instructions.forEach((instruction, index) => steps.push({ id: `${robot.id}-step-${index + 1}`, robotId: robot.id, stepOrder: index + 1, title: `Bước ${index + 1}`, instruction, illustration: {} }));
  library.push({ id: `${robot.id}-image`, robotId: robot.id, title: robot.name, type: 'image', url: robot.image, description: robot.summary });
}
const mapping = { buildTime: 'build_time', mainSensor: 'main_sensor', robotId: 'robot_id', componentId: 'component_id', stepOrder: 'step_order' };
// UTF-8 hex literals avoid dependence on NO_BACKSLASH_ESCAPES or quote handling.
const literal = value => value === null ? 'NULL' : typeof value === 'number' ? String(value) : `CONVERT(X'${Buffer.from(typeof value === 'object' ? JSON.stringify(value) : value).toString('hex')}' USING utf8mb4)`;
let sql = '-- Generated by node database/build-seed.cjs; load once after migration on an empty database.\nSET NAMES utf8mb4;\nSTART TRANSACTION;\n';
for (const [table, rows] of [['components', components], ['robots', robots], ['robot_components', relations], ['assembly_steps', steps], ['library_resources', library]]) {
  for (const row of rows) sql += `INSERT INTO ${table} (${Object.keys(row).map(k => '`' + (mapping[k] || k) + '`').join(', ')}) VALUES (${Object.values(row).map(literal).join(', ')});\n`;
}
sql += 'COMMIT;\n';
fs.writeFileSync(path.join(__dirname, 'seed.sql'), sql);
const migrations = fs.readdirSync(path.join(__dirname, 'migrations')).filter(name => name.endsWith('.sql')).sort();
fs.writeFileSync(path.join(__dirname, 'schema.sql'), migrations.map(name => fs.readFileSync(path.join(__dirname, 'migrations', name), 'utf8').replace(/\r\n/g, '\n').trimEnd()).join('\n\n') + '\n');
fs.writeFileSync(path.join(root, 'tests/content/seed-fixture.json'), JSON.stringify({ robots, components, relations, steps, library }, null, 2) + '\n');
