-- Hướng dẫn xử lý lỗi cho hai mẫu robot đợt 3; chạy sau seed-robots-phase3.sql.
-- Chỉ thêm nội dung tham khảo, không đọc telemetry và không sửa dữ liệu cũ.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('line-obstacle-issue-wobbles', 'line-obstacle', 'Cảm biến dò line', 'Robot lắc trái phải liên tục dù đường đi khá thẳng', 'Hai cảm biến đặt lệch độ cao hoặc biến trở ngưỡng chưa cân chỉnh; tốc độ động cơ quá cao khiến robot vượt quá vạch trước khi kịp phản hồi.', '1. Ngắt nguồn trước khi chỉnh vị trí. 2. Đặt hai cảm biến đối xứng và trong khoảng đọc của module. 3. Chỉnh biến trở trên nền trắng và vạch đen. 4. Giảm PWM, kiểm tra riêng trạng thái OUT trái/phải rồi chạy lại.', 'line-sensor', 15);
INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('line-obstacle-echo-missing', 'line-obstacle', 'Cảm biến siêu âm', 'Robot không dừng khi có vật cản phía trước', 'Chân TRIG/ECHO bị đảo hoặc gán sai D11/D12; cảm biến không có GND chung; mặt phát bị che hoặc ngưỡng khoảng cách đặt quá thấp.', '1. Ngắt nguồn và đối chiếu TRIG với D11, ECHO với D12. 2. Nối chung GND và kiểm tra VCC 5V. 3. Thử vật phẳng trước cảm biến trong vùng đo. 4. In/quan sát thời gian ECHO và chọn ngưỡng an toàn phù hợp.', 'hc-sr04', 16);
INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('line-obstacle-loses-track', 'line-obstacle', 'Điều khiển và động cơ', 'Robot né được vật cản nhưng chạy thẳng và không tìm lại vạch', 'Chương trình chưa có trạng thái tìm lại line; dây OUT hai cảm biến bị đổi; sau thao tác né robot quay quá xa hoặc chạy quá nhanh.', '1. Hạ tốc độ sau khi né. 2. Kiểm tra OUT trái/phải có đúng D2/D3. 3. Thêm bước quay/tìm chậm có đọc lại hai cảm biến. 4. Chỉ cho robot chạy tiếp khi đã xác nhận lại vạch.', 'l298n', 17);

INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('servo-scout-servo-reset', 'servo-scout', 'Servo và nguồn', 'Arduino khởi động lại hoặc servo rung khi bắt đầu quét', 'Dòng đỉnh servo làm sụt nguồn; đầu vào XL4015 không nằm trong dải của module; đầu ra chưa chỉnh đúng 5V; GND nguồn servo chưa nối chung hoặc càng servo đang bị kẹt cơ khí.', '1. Tắt nguồn trước khi kiểm tra cơ cấu. 2. Đối chiếu nguồn đầu vào với tài liệu đúng module; không lấy đầu vào XL4015 từ hộp 4AA 6V. 3. Đo đầu ra không tải, chỉnh đúng 5.0V rồi mới nối riêng servo. 4. Dùng nguồn đủ dòng, nối chung GND và kiểm tra cơ cấu không bị kẹt.', 'sg90', 18);
INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('servo-scout-ranging-noisy', 'servo-scout', 'Cảm biến siêu âm', 'Khoảng cách thay đổi mạnh giữa các lần quét cùng một hướng', 'Đọc ECHO khi servo chưa dừng; dây nguồn motor gây nhiễu; mặt phản xạ nghiêng hoặc nguồn 5V/GND không ổn định.', '1. Cho servo dừng một khoảng ngắn trước khi đo. 2. Dừng động cơ khi kiểm tra riêng cảm biến. 3. Đo vài mẫu hợp lệ và loại mẫu timeout. 4. Kiểm tra nguồn 5V, nối chung GND và hướng hai mắt HC-SR04 vuông góc với vật.', 'hc-sr04', 19);
INSERT IGNORE INTO troubleshooting_guides (`id`, `robot_id`, `component_group`, `symptom`, `possible_causes`, `resolution_steps`, `related_component_id`, `display_order`) VALUES ('servo-scout-turns-wrong-way', 'servo-scout', 'Servo và điều khiển', 'Robot thường rẽ về phía vừa đo thấy vật cản gần', 'Bảng ánh xạ góc trái/giữa/phải bị đảo do lắp servo ngược; chương trình chọn nhầm số đo hoặc servo chưa về đúng góc trước khi đọc.', '1. Quan sát hướng cảm biến tại từng lệnh góc khi tắt động cơ. 2. Ghi lại góc vật lý trái/giữa/phải. 3. Đợi servo ổn định rồi đo từng hướng riêng. 4. Chọn hướng có khoảng trống đủ ngưỡng và thử lại ở tốc độ thấp.', 'sg90', 20);

COMMIT;
