-- Seed bổ sung hai mẫu robot mới; chạy sau schema.sql và seed.sql.
-- Chỉ INSERT IGNORE, không sửa/xóa dữ liệu đã tồn tại; an toàn chạy lại.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT IGNORE INTO robots (`id`, `name`, `level`, `summary`, `image`, `build_time`, `main_sensor`, `skills`, `wiring`) VALUES ('line-obstacle', 'Robot dò line kết hợp tránh vật cản', 'Trung bình', 'Robot bám vạch bằng hai cảm biến hồng ngoại; khi HC-SR04 phát hiện chướng ngại trong ngưỡng, robot dừng, né vật cản rồi tìm lại vạch.', '/assets/images/robots/robot-line-obstacle.png', '90 – 120 phút', 'Cảm biến dò line hồng ngoại và HC-SR04', 'Kết hợp tín hiệu số và đo khoảng cách; ưu tiên sự kiện, điều khiển PWM và tìm lại quỹ đạo', '[{"pin":"D5","target":"L298N — ENA","note":"PWM chỉnh tốc độ bánh trái"},{"pin":"D6","target":"L298N — IN1","note":"Chọn chiều bánh trái"},{"pin":"D7","target":"L298N — IN2","note":"Chọn chiều bánh trái"},{"pin":"D8","target":"L298N — IN3","note":"Chọn chiều bánh phải"},{"pin":"D9","target":"L298N — IN4","note":"Chọn chiều bánh phải"},{"pin":"D10","target":"L298N — ENB","note":"PWM chỉnh tốc độ bánh phải"},{"pin":"D2","target":"Cảm biến dò line trái — OUT","note":"Ngõ vào số"},{"pin":"D3","target":"Cảm biến dò line phải — OUT","note":"Ngõ vào số"},{"pin":"D11","target":"HC-SR04 — TRIG","note":"Ngõ ra phát xung đo khoảng cách"},{"pin":"D12","target":"HC-SR04 — ECHO","note":"Ngõ vào đo độ rộng xung phản hồi"},{"pin":"5V","target":"VCC hai cảm biến line và HC-SR04","note":"Nguồn logic theo thông số module"},{"pin":"Hộp pin +","target":"L298N — Vs","note":"Nguồn động cơ; không đưa vào chân 5V Arduino"},{"pin":"GND","target":"Arduino, cảm biến, L298N và cực âm hộp pin","note":"Bắt buộc nối chung mass"}]');
INSERT IGNORE INTO robots (`id`, `name`, `level`, `summary`, `image`, `build_time`, `main_sensor`, `skills`, `wiring`) VALUES ('servo-scout', 'Robot quét hướng tránh vật cản', 'Trung bình', 'Servo SG90 quét HC-SR04 qua nhiều góc để so sánh khoảng trống, sau đó Arduino điều khiển xe né vật cản. Bản lắp thực tế cần thêm nguồn bàn DC 9V đủ dòng (không nằm trong bộ linh kiện tối thiểu); hộp pin 4AA 6V chỉ cấp phần động cơ.', '/assets/images/robots/robot-servo-scout.png', '100 – 130 phút', 'HC-SR04 gắn trên servo SG90', 'Đo thời gian truyền–nhận xung siêu âm, tạo PWM cho servo và chọn hướng theo số đo', '[{"pin":"D5","target":"L298N — ENA","note":"PWM chỉnh tốc độ bánh trái"},{"pin":"D6","target":"L298N — IN1","note":"Chọn chiều bánh trái"},{"pin":"D7","target":"L298N — IN2","note":"Chọn chiều bánh trái"},{"pin":"D8","target":"L298N — IN3","note":"Chọn chiều bánh phải"},{"pin":"D9","target":"L298N — IN4","note":"Chọn chiều bánh phải"},{"pin":"D10","target":"L298N — ENB","note":"PWM chỉnh tốc độ bánh phải"},{"pin":"D3","target":"SG90 — Signal","note":"PWM điều khiển góc quét; giới hạn cơ khí 0–180°"},{"pin":"D11","target":"HC-SR04 — TRIG","note":"Ngõ ra phát xung đo khoảng cách"},{"pin":"D12","target":"HC-SR04 — ECHO","note":"Ngõ vào đo độ rộng xung phản hồi"},{"pin":"Nguồn bàn DC 9V","target":"Arduino — VIN/DC jack và XL4015 — IN+","note":"Nguồn đủ dòng; giao dải danh định của XL4015 8–36V và Uno 7–12V; ngoài bộ linh kiện tối thiểu"},{"pin":"5V XL4015","target":"SG90 — VCC","note":"Đo đúng 5.0V; chỉ cấp servo, không nối vào chân 5V Arduino"},{"pin":"Arduino 5V","target":"HC-SR04 — VCC và L298N — logic 5V","note":"Không nối song song với nguồn logic 5V khác; cấu hình jumper 5V-EN theo đúng module L298N"},{"pin":"Hộp pin +","target":"L298N — Vs","note":"Nguồn 6V riêng cho động cơ; không đưa vào Arduino hoặc đầu vào XL4015"},{"pin":"GND","target":"Arduino, SG90, HC-SR04, L298N, DC-DC và cực âm các nguồn","note":"Bắt buộc nối chung mass"}]');

INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'chassis-2wd', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'arduino-uno', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'dc-motor', 2);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'wheel', 2);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'caster-wheel', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'line-sensor', 2);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'hc-sr04', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'l298n', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('line-obstacle', 'battery-holder', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'chassis-2wd', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'arduino-uno', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'dc-motor', 2);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'wheel', 2);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'caster-wheel', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'hc-sr04', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'sg90', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'l298n', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'battery-holder', 1);
INSERT IGNORE INTO robot_components (`robot_id`, `component_id`, `quantity`) VALUES ('servo-scout', 'power-5v', 1);

INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('line-obstacle-step-1', 'line-obstacle', 1, 'Gắn khung và truyền động', 'Gắn hai động cơ, bánh xe và bánh tự do vào khung xe.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('line-obstacle-step-2', 'line-obstacle', 2, 'Cố định bo mạch', 'Cố định Arduino Uno và L298N, chừa khoảng trống phía trước cho cảm biến.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('line-obstacle-step-3', 'line-obstacle', 3, 'Gắn hai loại cảm biến', 'Gắn hai cảm biến dò line ở mặt dưới phía trước và HC-SR04 hướng về phía trước.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('line-obstacle-step-4', 'line-obstacle', 4, 'Nối dây tín hiệu và nguồn', 'Đấu L298N vào D5–D10, cảm biến line vào D2/D3, HC-SR04 vào D11/D12; nối chung GND.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('line-obstacle-step-5', 'line-obstacle', 5, 'Nạp chương trình và thử', 'Nạp chương trình ưu tiên dừng/né khi vật cản gần, sau đó dò lại vạch; thử ở tốc độ thấp.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('servo-scout-step-1', 'servo-scout', 1, 'Gắn khung và truyền động', 'Lắp hai động cơ, bánh xe và bánh tự do vào khung xe.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('servo-scout-step-2', 'servo-scout', 2, 'Cố định bo mạch và nguồn', 'Cố định Arduino, L298N, hộp pin và module DC-DC ở vị trí chắc chắn.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('servo-scout-step-3', 'servo-scout', 3, 'Lắp cụm servo quét', 'Gắn servo SG90 ở đầu xe, lắp giá đỡ HC-SR04 lên càng servo và hướng hai mắt cảm biến ra trước.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('servo-scout-step-4', 'servo-scout', 4, 'Đấu nối có kiểm tra điện áp', 'Đấu L298N vào D5–D10, servo vào D3, TRIG/ECHO vào D11/D12. Bản lắp thực tế cần nguồn bàn DC 9V đủ dòng cấp cho VIN/DC jack Arduino và XL4015; hộp pin 4AA 6V chỉ cấp L298N Vs. Đo XL4015 đúng 5.0V rồi mới nối riêng SG90; cấp HC-SR04 và logic L298N từ Arduino 5V, kiểm tra jumper theo đúng module và nối chung GND.', '{}');
INSERT IGNORE INTO assembly_steps (`id`, `robot_id`, `step_order`, `title`, `instruction`, `illustration`) VALUES ('servo-scout-step-5', 'servo-scout', 5, 'Nạp chương trình và thử', 'Nạp chương trình quét các góc trái/giữa/phải, chờ servo ổn định rồi đo; thử né vật cản ở tốc độ thấp.', '{}');

COMMIT;
