package vn.edu.webpro.robotlab.dao;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import vn.edu.webpro.robotlab.model.AssemblySession;
import vn.edu.webpro.robotlab.model.SessionComponent;
import vn.edu.webpro.robotlab.model.SessionStep;

public final class AssemblySessionDao {
    private final DatabaseConnectionFactory connections;
    public AssemblySessionDao(DatabaseConnectionFactory connections){this.connections=connections;}
    public AssemblySession createOrResume(long userId,String robotId)throws SQLException{try(Connection c=connections.openConnection()){try(PreparedStatement s=c.prepareStatement("SELECT id,user_id,robot_id,status FROM assembly_sessions WHERE user_id=? AND robot_id=? AND status IN ('PREPARING','READY','IN_PROGRESS') ORDER BY updated_at DESC,id DESC LIMIT 1")){s.setLong(1,userId);s.setString(2,robotId);try(ResultSet r=s.executeQuery()){if(r.next())return hydrate(c,r);}}try(PreparedStatement s=c.prepareStatement("INSERT INTO assembly_sessions (user_id,robot_id,status) VALUES (?,?,'PREPARING')",Statement.RETURN_GENERATED_KEYS)){s.setLong(1,userId);s.setString(2,robotId);s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){k.next();return find(c,k.getLong(1),userId);}}}}
    public AssemblySession find(long id,long userId)throws SQLException{try(Connection c=connections.openConnection()){return find(c,id,userId);}}
    public List<AssemblySession> list(long userId)throws SQLException{List<AssemblySession> items=new ArrayList<>();try(Connection c=connections.openConnection();PreparedStatement s=c.prepareStatement("SELECT id,user_id,robot_id,status FROM assembly_sessions WHERE user_id=? ORDER BY updated_at DESC,id DESC")){s.setLong(1,userId);try(ResultSet r=s.executeQuery()){while(r.next())items.add(hydrate(c,r));}}return items;}
    public AssemblySession setComponent(long id,long userId,String componentId,boolean prepared)throws SQLException{return change(id,userId,(c,session)->{try(PreparedStatement s=c.prepareStatement("INSERT INTO session_components (session_id,robot_id,component_id,prepared) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE prepared=VALUES(prepared)")){s.setLong(1,id);s.setString(2,session.robotId());s.setString(3,componentId);s.setBoolean(4,prepared);s.executeUpdate();}});}
    public AssemblySession setStep(long id,long userId,String stepId,String status)throws SQLException{return change(id,userId,(c,session)->{try(PreparedStatement s=c.prepareStatement("INSERT INTO session_steps (session_id,robot_id,step_id,completed) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE completed=VALUES(completed)")){s.setLong(1,id);s.setString(2,session.robotId());s.setString(3,stepId);s.setBoolean(4,"COMPLETED".equals(status));s.executeUpdate();}});}
    public AssemblySession setVisual(long id,long userId,String componentId,boolean assembled)throws SQLException{return change(id,userId,(c,session)->{try(PreparedStatement s=c.prepareStatement(assembled?"INSERT INTO session_visual_parts (session_id,robot_id,component_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE component_id=VALUES(component_id)":"DELETE FROM session_visual_parts WHERE session_id=? AND component_id=?")){s.setLong(1,id);if(assembled){s.setString(2,session.robotId());s.setString(3,componentId);}else{s.setString(2,componentId);}s.executeUpdate();}});}
    private AssemblySession change(long id,long userId,Work work)throws SQLException{try(Connection c=connections.openConnection()){AssemblySession session=find(c,id,userId);if(session==null)return null;work.run(c,session);return find(c,id,userId);}}
    private AssemblySession find(Connection c,long id,long userId)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT id,user_id,robot_id,status FROM assembly_sessions WHERE id=? AND user_id=?")){s.setLong(1,id);s.setLong(2,userId);try(ResultSet r=s.executeQuery()){return r.next()?hydrate(c,r):null;}}}
    private AssemblySession hydrate(Connection c,ResultSet r)throws SQLException{long id=r.getLong("id");List<SessionComponent> components=new ArrayList<>();List<SessionStep> steps=new ArrayList<>();List<String> visual=new ArrayList<>();try(PreparedStatement s=c.prepareStatement("SELECT component_id,prepared FROM session_components WHERE session_id=?")){s.setLong(1,id);try(ResultSet rows=s.executeQuery()){while(rows.next())components.add(new SessionComponent(rows.getString(1),rows.getBoolean(2)));}}try(PreparedStatement s=c.prepareStatement("SELECT step_id,completed FROM session_steps WHERE session_id=?")){s.setLong(1,id);try(ResultSet rows=s.executeQuery()){while(rows.next())steps.add(new SessionStep(rows.getString(1),rows.getBoolean(2)?"COMPLETED":"PENDING"));}}try(PreparedStatement s=c.prepareStatement("SELECT component_id FROM session_visual_parts WHERE session_id=?")){s.setLong(1,id);try(ResultSet rows=s.executeQuery()){while(rows.next())visual.add(rows.getString(1));}}return new AssemblySession(id,r.getLong("user_id"),r.getString("robot_id"),r.getString("status"),components,steps,visual);}
    @FunctionalInterface private interface Work{void run(Connection connection,AssemblySession session)throws SQLException;}
}
